name: issue2docker-reproduce

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Number of the issue'
        required: true

jobs:
  reproduce_issue:
      runs-on: self-hosted
      steps:
        - name: Run issue2docker
          id: reproduce
          run: |
            if [ "$(sudo podman ps -aq)" ]; then
              sudo podman stop $(sudo podman ps -aq);
            fi
            sudo podman system prune -a -f
            sudo python3.9 /home/cluettgens/caesar/issue2docker-prototype/issue2docker.py --repo2docker_args "--engine=podman --user-id=87200024 --user-name=cluettgens" https://github.com/CamillaLu/gimli/issues/${{ github.event.inputs.issue_number }}
            sleep 5
            EXPECTED_RESULT=$(echo /home/cluettgens/caesar/issue2docker-prototype/result-{{ github.event.inputs.issue_number }}.txt)
            if sudo podman ps -a --format '{{.Names}}' | grep -q "^issue2docker$"; then
              ACTUAL_RESULT=$(sudo podman logs issue2docker)
              if [ "$EXPECTED_RESULT" = "$ACTUAL_RESULT" ]; then
                echo "Issue reproduced successfully."
                echo "reproduce_result=1" >> $GITHUB_OUTPUT
              else
                echo "Issue could not be reproduced automatically."
                 echo "reproduce_result=0" >> $GITHUB_OUTPUT
              fi
            else
              echo "No code and/or expected result to reproduce."
              echo "reproduce_result=2" >> $GITHUB_OUTPUT
            fi
        - name: Write artifact
          run: |
            echo "{\"issue_number\": \"${{ github.event.inputs.issue_number }}\", \"reproduce_result\": \"${{ steps.reproduce.outputs.reproduce_result }}\"}" > results.json
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: reproduce-issue-results
            path: |
              results.json
            
  
