name: pyGIMLi CI

env:
  # Current bug in openblas core detection: https://stackoverflow.com/a/66057286
  OPENBLAS_CORETYPE: ARMV8
  GIMLI_NUM_THREADS: 4
  OMP_THREAD_LIMIT: 4

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  pgcore:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # checks out all branches and tags
          path: source
      - name: Running cmake
        run: |
          mkdir -p build
          cd build
          CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake ../source
      - name: Build libgimli
        run: make -j 8 gimli
        working-directory: build
      - name: Build Python bindings
        run: make pygimli J=4
        working-directory: build
  pgtest:
    runs-on: self-hosted
    needs: pgcore
    steps:
      - name: Run Python tests
        run: OPENBLAS_CORETYPE="ARMV8" python3 -c "import pygimli; pygimli.test(show=False, onlydoctests=True)"
        working-directory: source
